[package]
name = "imgal"
version = "0.1.0"
edition = "2021"

[lib]
name = "imgal"
crate-type = ["cdylib", "rlib"]

[dependencies]
jni = "0.21.1"
pyo3 = { version = "0.24.1", features = ["extension-module"] }
